// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// intersect
arma::umat intersect(arma::umat first, arma::umat second);
RcppExport SEXP bcs_intersect(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::umat >::type first(firstSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type second(secondSEXP);
    __result = Rcpp::wrap(intersect(first, second));
    return __result;
END_RCPP
}
// setdiff
arma::umat setdiff(arma::umat first, arma::umat second);
RcppExport SEXP bcs_setdiff(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::umat >::type first(firstSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type second(secondSEXP);
    __result = Rcpp::wrap(setdiff(first, second));
    return __result;
END_RCPP
}
// FastLaplace
List FastLaplace(arma::mat PHI, arma::vec y, double sigma2, double eta, bool roundit, bool verbose);
RcppExport SEXP bcs_FastLaplace(SEXP PHISEXP, SEXP ySEXP, SEXP sigma2SEXP, SEXP etaSEXP, SEXP rounditSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type PHI(PHISEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type roundit(rounditSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(FastLaplace(PHI, y, sigma2, eta, roundit, verbose));
    return __result;
END_RCPP
}
