# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib bcs
#' @importFrom Rcpp sourceCpp
NULL

intersect <- function(first, second) {
    .Call('bcs_intersect', PACKAGE = 'bcs', first, second)
}

setdiff <- function(first, second) {
    .Call('bcs_setdiff', PACKAGE = 'bcs', first, second)
}

#'   Implements the fast Laplace algorithm.
#'
#'   This code implements the fast Laplace algorithm from [1], which is based on
#'   the BCS code available from [2].
#'
#' @param PHI measurement matrix.
#' @param y CS measurements.
#' @param sigma2 Initial noise variance.
#' @param eta Threshold in determining convergence of marginal likelihood.
#' @param verbose Print to screen which basis are added, re-estimated, or deleted.
#' @return A list containing the following elements:
#' \tabular{lll}{
#'   \code{weights} \tab \tab sparse weights\cr
#'   \code{used} \tab \tab the positions of sparse weights\cr
#'   \code{sigma2} \tab \tab re-estimated noise variance\cr
#'   \code{errbars} \tab \tab one standard deviation around the sparse weights\cr
#'   \code{alpha} \tab \tab sparse hyperparameters (1/gamma)
#' }
#' @references [1] S. D. Babacan, R. Molina, A. K. Katsaggelos. "Bayesian Compressive
#' Sensing using Laplace Priors",
#' @references [2] S. Ji, Y. Xue, L. Carin, "Bayesian Compressive Sensing," IEEE Trans.
#' Signal Processing, vol. 56, no. 6, June 2008.
#' @references [3] M. Tipping and A. Faul, “Fast marginal likelihood maximisation
#' for sparse Bayesian models,” in Proc. 9th Int. Workshop Artificial Intelligence
#' and Statistics, C. M. Bishop and B. J. Frey, Eds., 2003.
#' @export
FastLaplace <- function(PHI, y, sigma2, eta, verbose) {
    .Call('bcs_FastLaplace', PACKAGE = 'bcs', PHI, y, sigma2, eta, verbose)
}

